### ISSUE TITLE
設定をおしえてください

### ISSUE THREAD

**Issue by nhnmomonga** [birds-bgb-cards/birds.bgb.cards#1]
@tackman 
本リポジトリのgithub pagesの公開対象になっているブランチを教えていただけますでしょうか？
設定を見られる権限がないので、どのブランチにpushまたはpullrequestを出せばよいかわかりません。

**Comment by tackman** [comment]
masterにあるものが公開されるページとなります。masterにpushもしくはPRを出してください。

**Comment by tackman** [comment]
write権限を付与したので、nhnmomongaさんが直接編集できるようになったはずです
